### PR TITLE
Update IngressController manifest for unschedulable masters

### PR DESCRIPTION
**Pull request by nocturnalastro**

### CODE REVIEW

**Comment by halleelyasaf** [comment]
We used that and it’s work for us

**Comment by nocturnalastro** [comment]
@arjuhe

**Review by arjuhe — APPROVED** [review]
+1

**Comment by nocturnalastro** [comment]
@abays Thanks for this fix :)

**Comment by arjuhe** [comment]
@abays Thanks for the fix bud.

**Comment by abays** [comment]
My pleasure guys -- thanks for adding this!

**Pull request merged**
