### PR TITLE
introduce variable  hosts_discovery_minutes

### PR DESCRIPTION
**Pull request by newkit**
in order to make host discovery timeout configurable

### CODE REVIEW

**Review by nocturnalastro — CHANGES_REQUESTED** [review]
Can you move this into the defaults file that the default only in one place

**Comment by newkit** [comment]
@nocturnalastro Do you mean like this?

**Review by nocturnalastro — APPROVED** [review]
Yeah, like that there is only one place to change the defaults which makes life a lot easier and the tasks just look cleaner :)

**Comment by nocturnalastro** [comment]
@newkit Could squash your commits for me then I'll get it merged :)

**Comment by newkit** [comment]
@nocturnalastro All commits are squashed into one now.

**Pull request merged**
