### PR TITLE
Remove the need to define a tftp_host

### PR DESCRIPTION
**Pull request by nocturnalastro**
Add a default to tftp_host in TFTP_ROOT

### CODE REVIEW

**Review by halleelyasaf — APPROVED** [review]
LGTM

**Comment by natifridman** [comment]
Is there any way to make it more readable? It took me some time to understand what is going on here

**Comment by nocturnalastro** [comment]
Unfortunately aliasing hostvars in such a way would lead to all values being evaluated which has side effects.

**Review by natifridman — APPROVED** [review]
LGTM

**Review by arjuhe — APPROVED** [review]

**Pull request merged**
