### PR TITLE
Add 4.12.0 to allowed ocp versions.

### PR DESCRIPTION
**Pull request by nocturnalastro**

### CODE REVIEW

**Review by novacain1 — COMMENTED** [review]
LGTM although what about the doc (README)?

**Review by novacain1 — COMMENTED** [review]
Sample inventory too, just looking.

**Review by arjuhe — APPROVED** [review]
worked on my end.

**Comment by arjuhe** [comment]
@nocturnalastro merged. Please delete the branch when you are ready.

**Pull request merged**
